/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiTiktokEventRouteImport } from './routes/api/tiktok-event'
import { Route as ApiPixCreateRouteImport } from './routes/api/pix/create'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokEventRoute = ApiTiktokEventRouteImport.update({
  id: '/api/tiktok-event',
  path: '/api/tiktok-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixCreateRoute = ApiPixCreateRouteImport.update({
  id: '/api/pix/create',
  path: '/api/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/api/tiktok-event': typeof ApiTiktokEventRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/api/tiktok-event': typeof ApiTiktokEventRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/api/tiktok-event': typeof ApiTiktokEventRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/pix/create': typeof ApiPixCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/api/tiktok-event'
    | '/produto/$id'
    | '/api/pix/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/api/tiktok-event'
    | '/produto/$id'
    | '/api/pix/create'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/api/tiktok-event'
    | '/produto/$id'
    | '/api/pix/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiTiktokEventRoute: typeof ApiTiktokEventRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPixCreateRoute: typeof ApiPixCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok-event': {
      id: '/api/tiktok-event'
      path: '/api/tiktok-event'
      fullPath: '/api/tiktok-event'
      preLoaderRoute: typeof ApiTiktokEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix/create': {
      id: '/api/pix/create'
      path: '/api/pix/create'
      fullPath: '/api/pix/create'
      preLoaderRoute: typeof ApiPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ApiTiktokEventRoute: ApiTiktokEventRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPixCreateRoute: ApiPixCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
